name: Extract RootFS from Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "version.txt"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.$(dpkg --print-architecture) . -t arch:$(cat version.txt)

      - name: Extract RootFS
        run: |
          docker create --name arch arch:$(cat version.txt)
          docker export -o rootfs.$(dpkg --print-architecture).tar arch
          gzip rootfs.$(dpkg --print-architecture).tar

      - name: Upload RootFS
        uses: actions/upload-artifact@v3
        with:
          name: rootfs
          path: rootfs.*.tar.gz
