name: Extract RootFS from Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "version.txt"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build . -t arch:$(cat version.txt)
          docker build --platform linux/arm64 -f Dockerfile.arm64 . -t arch-arm64:$(cat version.txt)

      - name: Extract RootFS
        run: |
          docker create --name arch arch:$(cat version.txt)
          docker export -o rootfs.amd64.tar arch
          gzip rootfs.amd64.tar
          docker rm -f arch

          docker create --name arch-arm64 arch-arm64:$(cat version.txt)
          docker export -o rootfs.arm64.tar arch-arm64
          gzip rootfs.arm64.tar
          docker rm -f arch-arm64

      - name: Upload RootFS
        uses: actions/upload-artifact@v3
        with:
          name: rootfs
          path: rootfs.*.tar.gz
